# -*- coding: utf-8 -*-
"""assignment-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10H_s71bHiudHDocBv6jUXvQD2Bqkrro0

1 . Print the input text without vowels using List comprehensions

input = 'hai'
Expected output = h
"""

a = 'hai'
b = ''.join([char for char in a if char not in 'aeiouAEIOU'])
print(b)

"""2.Print only vowels from the text using List comprehensions
input = data
Expected output = dt

"""

a = 'data'
b = ''.join([char for char in a if char not in 'aeiouAEIOU'])
print(b)

"""3.
print each valu from the list with its index
input = [10,11,50,34]
Expected output = [100 , 111 , 502 , 343]


"""

a = [10,11,50,34]
b = [int(str(value) +str(index)) for index,value in enumerate(a)]
print(b)

"""4 . This is a Python Program to print all integers that aren’t divisible by either 2 or 3 and lies between 1 and 50.

"""

for i in range(1,51):
  if i % 2 !=0 and i %3 !=0:
    print(i)

"""5 . The program takes in an integer and prints the smallest divisor of the integer.

"""

#pass

"""6 . Write a Python program to check if it is a strong number or not .

"""

import math

a = int(input('Enter a number:'))
if sum(math.factorial(int(digit)) for digit in str (a)) == a:
  print(f'{a} is a strong number.')
else:
  print(f'{a} is not a strong number.')

"""7 . Write a Python program that takes input from the user and displays that input back in upper and lower cases.

"""

a ='python'
upper_case =a.upper()
lower_case =a.lower()
print(f'upper_case: {upper_case}')
print(f'lower_case:{lower_case}')

"""8.Write a Python program to remove spaces from a given string

input = united states
output = unitedstates

"""

a = 'united states'
b = a.replace(' ','')
print(b)

"""9 . Write a Python program to capitalize first and last letters of each word of a given string.

"""

#pass

"""10 . write a python program to find length of a string but should not use        len keyword



"""

a = 'hello world'
count = 0
for i in a:
  count += 1
print(count)

